services:
  article:
    build: 
      context: .
      dockerfile: ./apps/article/Dockerfile
      target: development
    command: npm run start:dev article
    env_file:
      - ./apps/article/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  content-seo:
    build: 
      context: .
      dockerfile: ./apps/content-seo/Dockerfile
      target: development
    command: npm run start:dev content-seo
    env_file:
      - ./apps/content-seo/.env
    ports:
      - '3005:3005'
    volumes:
      - .:/usr/src/app
  crawler:
    build: 
      context: .
      dockerfile: ./apps/crawler/Dockerfile
      target: development
    command: npm run start:dev crawler
    env_file:
      - ./apps/crawler/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
      target: development
    working_dir: /usr/src/app/client   # Set working directory
    command: npm run start             # Run command directly
    ports:
      - '8080:3000'
    volumes:
      - .:/usr/src/app